# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  facebook_app_id: <%= ENV["facebook_app_id"] %>
  facebook_app_secret: <%= ENV["facebook_app_secret"] %>
  secret_key_base: 49d5498c26d740be24dff37cd04f89c32656a16a3b291a09356261b0569ec05f6d6d9857882689589d7b992f1eac1526da34e23976189b7521d0c765336636b5

test:
  facebook_app_id: <%= ENV["facebook_app_id"] %>
  facebook_app_secret: <%= ENV["facebook_app_secret"] %>
  secret_key_base: 089aba54fc7e6a49aa1e1155d0b5180575626b868e4633a047bf351801528dd0f070db5874a389cfa88cf1a6bef7f0f69e5a2cec3ddd3d984e364fda1d654d7b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  facebook_app_id: <%= ENV["facebook_app_id"] %>
  facebook_app_secret: <%= ENV["facebook_app_secret"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
